name: RUW Caller
on:
  workflow_dispatch:

jobs:
  # calling:
  #   uses: briantist/gha-junk/.github/workflows/reusable.yml@main

  callsec:
    uses: ./.github/workflows/reuwsec.yml
    permissions:
      contents: read
    secrets:
      abc: ${{ secrets.SAMPLE_SECRET }}
