name: Buld a docsite out of multiple collections (sample)
on:
  workflow_dispatch:
    inputs:
      collections:
        description: Space separate list of collections to install and build.
        required: true

env:
  SURGE_SITE: ansible-test-multi-col-site.surge.sh
  ANSIBLE_COLLECTIONS_PATHS: ${{ github.workspace }}

jobs:
  build-docs:
    permissions:
      contents: read
    name: Build Ansible Docs
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python }}

      - name: Install Ansible
        run: pip install https://github.com/ansible/ansible/archive/${{ inputs.ansible-ref }}.tar.gz --disable-pip-version-check

      - name: Install collections
        shell: bash
        run: ansible-galaxy collection install ${{ github.event.inputs.collections }} -p "$ANSIBLE_COLLECTIONS_PATHS"

      - name: Initialize the build environment
        id: init
        uses: ansible-collections/community.hashi_vault/.github/actions/docs/ansible-docs-build-init@main
        with:
          collections: ${{ github.event.inputs.collections }}
          # dest-dir: ${{ steps.vars.outputs.init-dir }}
          # skip-init: ${{ steps.vars.outputs.skip-init }}

      - name: Build
        id: build
        uses: ansible-collections/community.hashi_vault/.github/actions/docs/ansible-docs-build-html@main
        with:
          build-script: ${{ steps.init.outputs.build-script }}
          build-html: ${{ steps.init.outputs.build-html }}
          # artifact-name: ${{ inputs.artifact-name }}

    # uses: ansible-collections/community.hashi_vault/.github/workflows/_shared-docs-build-pr.yml@main
    # with:
    #   init-dest-dir: docs/preview
    #   render-file-line: '> * `$<status>` [$<path_tail>](https://community-hashi-vault-pr${{ github.event.number }}.surge.sh/$<path_tail>)'

  publish-docs:
    permissions:
      contents: read
    needs: build-docs
    name: Publish Ansible Docs
    uses: ansible-collections/community.hashi_vault/.github/workflows/_shared-docs-build-publish-surge.yml@main
    with:
      artifact-name: ${{ needs.build-docs.outputs.artifact-name }}
      surge-site-name: ansible-test-multi-col-site.surge.sh
      # action: ${{ (github.event.action == 'closed' || needs.build-docs.outputs.changed != 'true') && 'teardown' || 'publish' }}
    secrets:
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
