name: Buld a docsite out of multiple collections (sample)
on:
  workflow_dispatch:
    inputs:
      collections:
        description: Space separate list of collections to install and build.
        required: true
      ansible-ref:
        description: the branch or ref to install Ansible from.
        required: false
        default: milestone

env:
  SURGE_SITE: ansible-test-multi-col-site.surge.sh
  ANSIBLE_COLLECTIONS_PATHS: ${{ github.workspace }}

jobs:
  build-docs:
    permissions:
      contents: read
    outputs:
      artifact-name: ${{ steps.build.outputs.artifact-name }}
    name: Build Ansible Docs
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python }}

      - name: Install Ansible
        run: pip install https://github.com/ansible/ansible/archive/${{ github.event.inputs.ansible-ref }}.tar.gz --disable-pip-version-check

      - name: Install collections
        shell: bash
        run: ansible-galaxy collection install ${{ github.event.inputs.collections }} -p "$ANSIBLE_COLLECTIONS_PATHS"

      - name: Initialize the build environment
        id: init
        uses: ansible-community/github-docs-build/actions/ansible-docs-build-init@main
        with:
          collections: ${{ github.event.inputs.collections }}

      - name: Build
        id: build
        uses: ansible-community/github-docs-build/actions/ansible-docs-build-html@main
        with:
          build-script: ${{ steps.init.outputs.build-script }}
          build-html: ${{ steps.init.outputs.build-html }}

  publish-docs:
    permissions:
      contents: read
    needs: build-docs
    name: Publish Ansible Docs
    uses: briantist/github-docs-build/.github/workflows/_shared-docs-build-publish-surge.yml@deps/pin-surge-colors
    with:
      artifact-name: ${{ needs.build-docs.outputs.artifact-name }}
      surge-site-name: ansible-test-multi-col-site.surge.sh
    secrets:
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
