---
on:
  workflow_call:
    secrets:
      abc:
        required: true

jobs:
  sampsec:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - shell: pwsh
        run: |
          '${{ secrets.abc }}'.Length
          '${{ secrets.SAMP2 }}'.Length
