---
name: Scheduled
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - shell: pwsh
        run: |
          @'
          ${{ toJSON(github) }}
          '@

      - uses: actions/github-script@v5
        with:
          script: |
            var gh = ${{ toJSON(github) }}

            repo = gh.event.repo.name
            if (repo == '') {
                repo = gh.repository.split('/')[1]
            }

            core.warning(`repo: ${repo}`)
