---
name: Scheduled
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - shell: pwsh
        run: |
          @'
          ${{ toJSON(github) }}
          '@
