---
name: scripty
on:
  workflow_dispatch:
    inputs:
      dummy:
        required: false
        description: dummy


jobs:
  scripty:
    runs-on: ubuntu-latest
    steps:
      - name: script
        id: script
        uses: actions/github-script@v5
        with:
          script: |
            var dummy = context.payload.inputs.dummy
            dummy = dummy.replace('.', '/')
            return {
                context: context,
                github: github,
                test1: dummy
            }

      - run: |
          echo <<EOF
          ${{ toJSON(fromJSON(steps.script.outputs.result)) }}
          EOF
