---
name: scripty
env:
  TEST2: '@@@@@@@'
on:
  workflow_dispatch:
    inputs:
      dummy-thing:
        required: false
        description: dummy


jobs:
  scripty:
    runs-on: ubuntu-latest
    steps:
      - name: script
        id: script
        uses: actions/github-script@v5
        with:
          script: |
            var dummy = context.payload.inputs['dummy-thing']
            dummy = dummy.replace('.', '/')
            return {
                context: context,
                github: github,
                env: process.env,
                test1: dummy,
                test2: process.env.TEST2
            }

      - run: |
          echo <<EOF
          ${{ toJSON(fromJSON(steps.script.outputs.result)) }}
          EOF
