name: test surge
on:
  workflow_dispatch:

jobs:
  surge:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Surge
        run: npm ci -g surge

      - run: surge whoami
