name: test surge
on:
  workflow_dispatch:

jobs:
  surge:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Surge
        run: |
          npm install -g colors@1.4.0 surge
          npm list -g | grep colors

      - run: surge whoami
