on:
  workflow_dispatch:

permissions:
  contents: none

jobs:
  _1up:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir dir
          echo a > dir/a.txt
          echo b > dir/b.txt
          tree

      - uses: actions/upload-artifact@v3
        with:
          name: art
          path: dir/

  _1down:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: art

      - name: No path tree
        run: tree

      - uses: actions/download-artifact@v3
        with:
          name: art
          path: dir/

      - name: Path tree
        run: tree
