---
name: WSL
on:
  pull_request:
    types: ['opened', 'synchronize']

jobs:
  Windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-2019
          - windows-2022
        distro:
          - Ubuntu-20.04
          - Debian
    defaults:
      run:
        shell: wsl-bash {0}

    steps:
      - name: Create an admin user
        shell: cmd
        run: |
          net user admin pass123@ /add /y
          net localgroup Administrators admin /add

      - name: Set up the runner for PowerShell remoting
        shell: powershell
        continue-on-error: true
        run: |
          $sb = [ScriptBlock]::Create((New-Object System.Net.Webclient).DownloadString('https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1'))
          & $sb -Verbose -ForceNewSSLCert 4>&1

      - uses: actions/checkout@v2

      - uses: Vampire/setup-wsl@v1
        with:
          distribution: ${{ matrix.distro }}
          additional-packages: |
            git
            coreutils
            python3
            python3-pip

      - name: Let's install Ansible and stuff?
        timeout-minutes: 2
        run: |
          pip install --upgrade pip
          pip install ansible-core pywinrm pypsrp
          ansible --version
          #timeout 2m bash -c 'ansible-galaxy collection install community.windows ansible.windows' && echo yay || echo oh
          timeout 5s pwd

      - name: Can we run something?
        run: |
          pwd
          ls -alh
          ansible-inventory -i inventory --graph
          ansible windows.local -i inventory -m gather_facts -e "ansible_password=pass123@"
